version: '3.5'
services:
  walletService_db:
    container_name: walletService_db
    image: postgres:16.0-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_USER: admin
      POSTGRES_DB: walletServiceDB
    ports:
      - "54321:5432"
  walletService_db_admin:
    container_name: walletService_db_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@walletservice.ru
      PGADMIN_DEFAULT_PASSWORD: Aa123456
    ports:
      - "5051:80"